version: "3.9"
services:
  flask_fibonacci:
    image: flask-fibonacci
    container_name: flask-fibonacci
    build: .
    ports:
      - "5000:5000"
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 app:app
